<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.zimo</groupId>
        <artifactId>agent-trace</artifactId>
        <version>1.0.0</version>
    </parent>

    <artifactId>agent-trace-autoconfig</artifactId>
    <name>module-agent-deploy-autoconfig</name>
    <description>多智能体部署平台自动装配</description>

    <dependencies>
        <dependency>
            <groupId>com.zimo</groupId>
            <artifactId>agent-trace-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.zimo</groupId>
            <artifactId>framework-autoconfig</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
